

app:
  name: CurrencyExchangeApp
  port: :8080

database:
  dsn: "root:123456@tcp(127.0.0.1:3308)/exchange?charset=utf8mb4&parseTime=True&loc=Local"
  MaxIdleConns: 10
  MaxOpenConns: 100
redis:
  addr: "localhost:6379"
  DB: 0
  Password: ""


